version: '3'

services:
  kafka:
    image: mattmoore/kafka
    ports:
      - '9092:9092'
    entrypoint: '/docker-entrypoint.sh'
    depends_on:
      - 'zookeeper'
  zookeeper:
    image: mattmoore/kafka-zookeeper
    ports:
      - '2181:2181'
    entrypoint: '/docker-entrypoint.sh'
