version: '3'

services:
  kafka-client:
    image: mattmoore/kafka-broker
    depends_on:
      - 'broker'
      - 'zookeeper'

  broker:
    image: mattmoore/kafka-broker
    ports:
      - '9092:9092'
    entrypoint:
      - 'sh'
      - '/kafka/bin/kafka-server-start.sh'
      - '/kafka/config/server.properties'
      - '--override'
      - 'zookeeper.connect=zookeeper:2181'
      - '--override'
      - 'listeners=EXTERNAL://0.0.0.0:9092,INTERNAL://broker:29092'
      - '--override'
      - 'advertised.listeners=EXTERNAL://localhost:9092,INTERNAL://broker:29092'
      - '--override'
      - 'listener.security.protocol.map=EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT'
      - '--override'
      - 'inter.broker.listener.name=INTERNAL'
    depends_on:
      - 'zookeeper'

  zookeeper:
    image: mattmoore/kafka-zookeeper
    ports:
      - '2181:2181'
    entrypoint:
      - 'sh'
      - '/kafka/bin/zookeeper-server-start.sh'
      - '/kafka/config/zookeeper.properties'
